# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

# GPIO (button + LED)
CONFIG_GPIO=y

# Use Zephyr minimal libc to avoid Picolibc lock retargeting conflicts
CONFIG_MINIMAL_LIBC=y
CONFIG_PICOLIBC=n
CONFIG_NEWLIB_LIBC=n

